### ISSUE TITLE
webdriver issues across all platforms

### ISSUE THREAD

**Issue by shariliu** [jfkominsky/PyHab#31]
Hi Jonathan. First time trying this out, and I was able to download Selenium and moved the relevant drivers into bin, link up my stim w/ slide numbers, and I keep getting stuck when I'm actually going to run the expt.

- For Firefox, I'm running into this issue: https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS/Errors/CORSMissingAllowOrigin
- For Chrome, I'm getting a msg that says `OSError: [Errno 86] Bad CPU type in executable: 'chromedriver'`
- For Safari, I'm seeing a long msg but in short, I need to stop automation in order to start the presentation, which I think (?) then stops the process by which Psychopy is talking w/ slides.com. Here's the whole msg:
```
 Traceback (most recent call last):
  File "/Users/ShariLiu/Dropbox (MIT)/Research/Studies/_NIRS/Goals-Simple/goals-simple/goals-simpleLauncher.py", line 78, in <module>
    run()
  File "/Users/ShariLiu/Dropbox (MIT)/Research/Studies/_NIRS/Goals-Simple/goals-simple/goals-simpleLauncher.py", line 40, in run
    experiment.run()
  File "/Users/ShariLiu/Dropbox (MIT)/Research/Studies/_NIRS/Goals-Simple/goals-simple/PyHab/PyHabClass.py", line 2311, in run
    self.SetupWindow()
  File "/Users/ShariLiu/Dropbox (MIT)/Research/Studies/_NIRS/Goals-Simple/goals-simple/PyHab/PyHabClass.py", line 2415, in SetupWindow
    self.nextArrow = self.browser.find_element_by_css_selector("button.navigate-right")
  File "/Applications/PsychoPy.app/Contents/Resources/lib/python3.6/selenium/webdriver/remote/webdriver.py", line 598, in find_element_by_css_selector
    return self.find_element(by=By.CSS_SELECTOR, value=css_selector)
  File "/Applications/PsychoPy.app/Contents/Resources/lib/python3.6/selenium/webdriver/remote/webdriver.py", line 978, in find_element
    'value': value})['value']
  File "/Applications/PsychoPy.app/Contents/Resources/lib/python3.6/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/Applications/PsychoPy.app/Contents/Resources/lib/python3.6/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: 
```

Decided to use issues in case this is useful for others in the future. If you have any suggestions for things I should try, let me know!

**Comment by jfkominsky** [comment]
I'm not 100% sure about the FireFox or Safari errors, but the Chrome one I have a pretty good guess about what's going on. There are two different versions of chromedriver for Mac, one for Intel-based Macs (i.e. pretty much everything pre-2020), and one for newer M1-based Macs. I'm about 90% certain this error is a result of getting the wrong one for your system. 

The current release version of Chrome is 92, so if you go here you should see a list of the different operating system versions: https://chromedriver.storage.googleapis.com/index.html?path=92.0.4515.107/

If you're using an intel-based Mac, you should get the one that's just called "mac64". If you have a newer M1-based Mac, get the one called "mac64_m1". If you aren't sure, you should be able to find out by going to "about this Mac" and looking at the processor. Let me know if that works and if so I'll close the issue and update my documentation.

**Comment by shariliu** [comment]
That solved it! Thanks - may get in touch about other things but want to give it a try myself first. Psychopy is definitely talking to Chrome (e.g. 'end expt' causes the slideshow to end too)
