### ISSUE TITLE
'auto-redo if min on-time crit not met' checkbox triggering error

### ISSUE THREAD

**Issue by shariliu** [jfkominsky/PyHab#32]
I and @sabrinapiccolo are currently using the latest online version of pyhab to set up a VOE experiment. I have found that if I have the 'automatically redo trial if min on-time criterion not met' box checked in the trial settings, as soon as I indicate an off look, the control window disappears and I get the following console output. If this box is unchecked, then the experiment runs fine. Dropbox link to project: https://www.dropbox.com/sh/w4u9aj21cy3ph49/AABHC_L3XA68EiHwJarZcI8-a?dl=0

```
2021-11-05 17:39:18.308 python[8692:274783] ApplePersistenceIgnoreState: Existing state will not be touched. New state will be written to /var/folders/18/nbn3vbdx2jv900brph6lq3180000gn/T/org.opensciencetools.psychopy.savedState
Traceback (most recent call last):
  File "/Users/ShariLiu/Dropbox (MIT)/Research/Studies/_NIRS/Goals-Simple/github:goal-simple/goal-simpleLauncher.py", line 78, in <module>
    run()
  File "/Users/ShariLiu/Dropbox (MIT)/Research/Studies/_NIRS/Goals-Simple/github:goal-simple/goal-simpleLauncher.py", line 45, in run
    run()
  File "/Users/ShariLiu/Dropbox (MIT)/Research/Studies/_NIRS/Goals-Simple/github:goal-simple/goal-simpleLauncher.py", line 40, in run
    experiment.run()
  File "/Users/ShariLiu/Dropbox (MIT)/Research/Studies/_NIRS/Goals-Simple/github:goal-simple/PyHab/PyHabClass.py", line 2323, in run
    self.SetupWindow()
  File "/Users/ShariLiu/Dropbox (MIT)/Research/Studies/_NIRS/Goals-Simple/github:goal-simple/PyHab/PyHabClass.py", line 2467, in SetupWindow
    self.doExperiment()  # Get this show on the road!
  File "/Users/ShariLiu/Dropbox (MIT)/Research/Studies/_NIRS/Goals-Simple/github:goal-simple/PyHab/PyHabClass.py", line 1223, in doExperiment
    x = self.doTrial(trialNum, self.actualTrialOrder[trialNum - 1], disMovie)  # the actual trial, returning one of four status values at the end
  File "/Users/ShariLiu/Dropbox (MIT)/Research/Studies/_NIRS/Goals-Simple/github:goal-simple/PyHab/PyHabClass.py", line 1454, in doTrial
    if localType in self.autoRedo and nowO
ff >= self.onTimeDeadline[localType] and not deadlineChecked:
KeyError: 'fam'
##### Experiment ended. #####
```

**Comment by jfkominsky** [comment]
Thanks for spotting this! The auto-redo system in the builder is set up so it can check during the trial or check at the end of the trial, but in this code it was assuming it would always be used to check during a trial. If you grab the most recent version of PyHabClass.py from the online-edition branch and replace the PyHabClass file in your experiment's PyHab folder, it should now work as intended.
